### ISSUE TITLE
Deployment: Serverwechsel

### ISSUE THREAD

**Issue by Nachti-galleR** [mi-classroom/mi-web-technologien-beiboot-ss2022-SickxX#3]
Wechsel weg von AWS, weil freie Nutzung Ende Mai ausläuft.

**Comment by SickxX** [comment]
andererseits geht sicher auch einfach ein neuer Account bei aws, muss ich mal überlegen.

**Comment by Nachti-galleR** [comment]
Erstmal auf Githubpages deployed.
